#!/bin/bash

#*******************************************
# SYSTEM VERSION
#
# Compare transcripts generated by StringTie 
# 
#*******************************************

echo "Teste1"

REFGTF="/Volumes/HD3/Referencias/gencode.v30.annotation.gtf" #Reference fasta file
REFCENTRAL="/Volumes/HD3/Referencias/RNACentral_homo_sapiens.GRCh38.gff3"
WORKDIR="/Volumes/HD3/Brohl_chr/Data/assembly"

STRINGTIE="/Users/rafaelcoan/Programas/stringtie-1.3.4d.OSX_x86_64/stringtie"
GFFCOMPARE="/Users/rafaelcoan/Programas/gffcompare-0.10.4/gffcompare"

N=1
MAXJOBS=10

function multiple_threads {
    if [ "$N" -lt "$MAXJOBS" ] ; then
        N=$((N + 1))
	else
        wait
    fi
}

echo "********************************"
echo "MERGE TRANSCRIPTS WITH STRINGTIE"
echo "********************************"

date

DATE=$(date "+%Y-%m-%d")

cd ${WORKDIR}

$STRINGTIE --merge -p 20 -G $REFGTF -o stringtie_merged_${DATE}.gtf gtf-list.txt

echo "*************************************"
echo "COMPARING TRANSCRIPTS WITH GFFCOMPARE"
echo "*************************************"

date

# Comparação da montagem nova contra o gencode v30
$GFFCOMPARE -R -r $REFGTF -o compare_gencode_${DATE} stringtie_merged_${DATE}.gtf

# Comparação da montagem nova contra a RNACentral v16
$GFFCOMPARE -R -r $REFCENTRAL -o compare_central_${DATE} stringtie_merged_${DATE}.gtf
